"""Render a PackedContext as a clean, pasteable Markdown document."""
from __future__ import annotations

from pathlib import Path

from .packer import PackedContext

# Map file extensions → fenced code block language hints
_LANG_MAP = {
    ".py": "python", ".js": "javascript", ".ts": "typescript",
    ".jsx": "jsx", ".tsx": "tsx", ".mjs": "javascript",
    ".rs": "rust", ".go": "go", ".c": "c", ".cpp": "cpp",
    ".h": "c", ".hpp": "cpp", ".cs": "csharp", ".java": "java",
    ".kt": "kotlin", ".swift": "swift", ".rb": "ruby",
    ".php": "php", ".lua": "lua", ".ex": "elixir", ".exs": "elixir",
    ".scala": "scala", ".zig": "zig", ".dart": "dart",
    ".html": "html", ".css": "css", ".scss": "scss", ".sass": "sass",
    ".vue": "vue", ".svelte": "svelte",
    ".yaml": "yaml", ".yml": "yaml", ".toml": "toml",
    ".json": "json", ".sh": "bash", ".bash": "bash",
    ".zsh": "bash", ".ps1": "powershell",
    ".md": "markdown", ".mdx": "markdown", ".rst": "rst",
    ".tf": "hcl", ".hcl": "hcl",
}


def render(
    ctx: PackedContext,
    query: str,
    base: Path,
    show_scores: bool = False,
) -> str:
    """Return the full context document as a Markdown string."""
    lines = []

    # ── Header ─────────────────────────────────────────────────────────────────
    lines.append(_header(ctx, query, base))

    # ── Files ──────────────────────────────────────────────────────────────────
    for fp, content, score in ctx.included:
        rel = str(fp.relative_to(base))
        lang = _LANG_MAP.get(fp.suffix.lower(), "")
        score_tag = f"  <!-- score: {score:.1f} -->" if show_scores else ""
        lines.append(f"\n---\n")
        lines.append(f"## `{rel}`{score_tag}\n")
        lines.append(f"```{lang}")
        lines.append(content.rstrip())
        lines.append("```")

    # ── Footer ─────────────────────────────────────────────────────────────────
    if ctx.excluded:
        lines.append("\n---\n")
        lines.append("## Excluded files\n")
        for fp, reason in ctx.excluded:
            rel = str(fp.relative_to(base))
            lines.append(f"- `{rel}` — {reason}")

    lines.append(
        f"\n\n<!-- Generated by context-pack {_version()} | "
        f"{len(ctx.included)} files | ~{ctx.total_tokens:,} tokens -->"
    )

    return "\n".join(lines)


def _header(ctx: PackedContext, query: str, base: Path) -> str:
    pct = ctx.utilisation_pct
    bar_filled = int(pct / 5)
    bar = "█" * bar_filled + "░" * (20 - bar_filled)

    return (
        f"# AI Context Pack\n\n"
        f"**Query:** {query}\n\n"
        f"| Stat | Value |\n"
        f"|------|-------|\n"
        f"| Files included | {len(ctx.included)} |\n"
        f"| Files excluded | {len(ctx.excluded)} |\n"
        f"| Estimated tokens | ~{ctx.total_tokens:,} |\n"
        f"| Token budget | {ctx.budget_tokens:,} |\n"
        f"| Budget used | {pct:.1f}% |\n\n"
        f"`{bar}` {pct:.0f}%\n\n"
        f"> Paste everything below the horizontal rule into your AI assistant.\n"
    )


def _version() -> str:
    try:
        from context_pack import __version__
        return __version__
    except Exception:
        return "?"
